apiVersion: v1
kind: Service
metadata:
  name: cr-cdc-service
  namespace: code-redemption
  labels:
    app: cr-cdc-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: cr-cdc-service