apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: code-redemption
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: docker.io/makalaoscar/oscar-docker:cr-api-gateway
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /workspace/config
              readOnly: true
          ports:
            - containerPort: 80
#          livenessProbe:
#            httpGet:
#              path: /management/health
#              port: 80
#            initialDelaySeconds: 45
#          readinessProbe:
#            httpGet:
#              path: /management/info
#              port: 80
#            initialDelaySeconds: 45
          env:
            - name: SERVER_PORT
              value: '80'
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: 'false'
      imagePullSecrets:
        - name: docker-secret-registry
      volumes:
        - name: config
          configMap:
            name: api-gateway
            items:
              - key: application.yaml
                path: application.yaml
