apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: code-redemption
  labels:
    app: api-gateway
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: api-gateway