apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: code-redemption
  labels:
    app: order-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: order-service