apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: code-redemption
  labels:
    app: kafka
    component: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:5.5.2
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: zookeeper-persistent-storage
      volumes:
        - name: zookeeper-persistent-storage
          persistentVolumeClaim:
            claimName: zookeeper