apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: code-redemption
  labels:
    app: kafka
    component: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: kafka-port
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka
    component: kafka
