apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka
  namespace: code-redemption
  labels:
    app: kafka
    component: kafka
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
