apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  namespace: code-redemption
  labels:
    app: user-service
data:
  application.yaml: |-
    server:
      port: 2678
    spring:
      application:
        name: user-service
      main:
        banner-mode: off
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: http://keycloak:8080/auth/realms/azamCodeRedemption/protocol/openid-connect/certs
    oauth-client-id: codeRedemptionAuth
    logging:
      level:
        org.springframework.web: INFO
        org.springframework.security: INFO
        org.springframework.security.oauth2: INFO