apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: code-redemption
  labels:
    app: user-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: user-service