server:
  port: 2678
spring:
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${DOCKER_HOST_IP:localhost}:8090/auth/realms/azamCodeRedemption/protocol/openid-connect/certs
oauth-client-id: codeRedemptionAuth
oauth-client-secret: a3E1T9JL4BIEVb57CSvpn2hobp76KVIc
oauth-client-endpoint: http://${DOCKER_HOST_IP:localhost}:8090/auth/realms/azamCodeRedemption/protocol/openid-connect/token
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO