apiVersion: v1
kind: Service
metadata:
  name: voucher-history-service
  namespace: code-redemption
  labels:
    app: voucher-history-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voucher-history-service