apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service
  namespace: code-redemption
  labels:
    app: account-service
data:
  application.yaml: |-
    spring:
      application:
        name: cr-account-service
      datasource:
        url: jdbc:mysql://172.16.115.6:3306/cr_account_service
        username: cr_account_service_user
        password: cr_account_service_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          max-lifetime: 600000
      jpa:
        generate-ddl: true
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: http://keycloak:8080/auth/realms/azamCodeRedemption/protocol/openid-connect/certs
    eventuatelocal:
      kafka:
        bootstrap:
          servers: kafka:29092
      zookeeper:
        connection:
          string: zookeeper:2181
    eventuate:
      database:
        schema: cr_account_service
    logging:
      level:
        org.springframework.orm.jpa: INFO
        org.hibernate.SQL: DEBUG
        io.eventuate: DEBUG
        io.eventuate.tram: DEBUG
        com.divforce.cr: DEBUG

    vendors:
      disbursement:
        endpoint: https://172.16.4.5:8243/codedisburse/1.0.0
        headers:
          Authorization: "Bearer 6b50540b-b360-3970-92fd-88e3b4e4429e"
        responseMap:
          externalTxnOne: transactionId
          externalTxnTwo: serviceRequestId
          transactionStatus: status
          message: message
        template: |
          {"serviceCode":"CODEDISB","bearerCode":"USSD","transactionAmount":"#{amount}","currency":"101","externalReferenceId":"#{transactionId}","source":"CODE_REDEMPTION","remarks":"Codedisburse","transactionMode":"Codedisburse","initiator":"transactor","language":"sw","transactor":{"idType":"mobileNumber","idValue":"1780100100","productId":"12","mpin":"1357","tpin":"1357"},"receiver":{"idType":"mobileNumber","idValue":"#{mobile}","productId":"12"}}
    debug: true