apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: code-redemption
  labels:
    app: account-service
spec:
  selector:
    matchLabels:
      app: account-service
  replicas: 1
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: docker.io/makalaoscar/oscar-docker:cr-account-service
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /workspace/config
              readOnly: true
          ports:
            - containerPort: 80
          #          livenessProbe:
          #            httpGet:
          #              path: /management/health
          #              port: 80
          #            initialDelaySeconds: 45
          #          readinessProbe:
          #            httpGet:
          #              path: /management/info
          #              port: 80
          #            initialDelaySeconds: 45
          env:
            - name: SERVER_PORT
              value: '80'
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: 'false'
      imagePullSecrets:
        - name: docker-secret-registry
      volumes:
        - name: config
          configMap:
            name: account-service
            items:
              - key: application.yaml
                path: application.yaml
