spring:
  application:
    name: cr-voucher-service
  datasource:
    url: jdbc:mysql://${DOCKER_HOST_IP:localhost}:3307/voucher_service
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 30000
      max-lifetime: 1800000

  jpa:
    generate-ddl: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${DOCKER_HOST_IP:localhost}:8090/auth/realms/azamCodeRedemption/protocol/openid-connect/certs


  flyway:
    locations: classpath:flyway/{vendor}
    baseline-on-migrate: true
    baseline-version: 0

eventuatelocal:
  kafka:
    bootstrap:
      servers: ${DOCKER_HOST_IP:localhost}:9092
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP:localhost}:2181

eventuate:
  database:
    schema: none


logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    io.eventuate: INFO
    io.eventuate.tram: INFO
    com.divforce.cr: DEBUG
    org.springframework.beans: 'WARN'
    org.springframework.context: 'WARN'
    org.springframework.jmx: 'WARN'
    org.springframework.web: 'WARN'
    org.springframework.security: 'WARN'
    org.springframework.integration: 'WARN'
    org.springframework.boot: 'WARN'
server:
  port: 9877