apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  mysql-claim
  namespace: code-redemption
  labels:
    app:  mysql-claim
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
