spring:
  application:
    name: cr-order-service
  datasource:
    url: jdbc:mysql://${DOCKER_HOST_IP:localhost}:3306/order_service
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 30000
      max-lifetime: 1800000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${DOCKER_HOST_IP:localhost}:8090/auth/realms/azamCodeRedemption/protocol/openid-connect/certs


  flyway:
    locations: classpath:flyway/{vendor}
    baseline-on-migrate: true
    baseline-version: 0

eventuatelocal:
  kafka:
    bootstrap:
      servers: ${DOCKER_HOST_IP:localhost}:9092
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP:localhost}:2181

eventuate:
  database:
    schema: none

logging:
  level:
    com.ftj.trivia: INFO
    org.springframework.orm.jpa: INFO
    org.hibernate.SQL: INFO
    io.eventuate: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO

server:
  port: 9876

notification:
  voucher_request_submitted: Ndugu mteja ombi lako linashughulikiwa utapokea ujumbe hivi punde.
  voucher_not_found_sw: Ndugu mteja namba yako ya bahati haijafanikiwa. Endelea kununua vinywaji vya Azam uweze kupata rejesho kwenye akaunti yako ya Azampesa.
  voucher_used_sw: Ndugu mteja namba yako ya bahati imeshatumika. Endelea kununua vinywaji vya Azam m na ufuruhie huduma zetu.
