version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    networks:
      - coderedemption
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_DATABASE: keycloak
      DB_USER: mysqluser
      DB_PASSWORD: Mysqlpw@@123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - '8080:8080'
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - mariadb
networks:
  coderedemption:
    external: true