version: '3.8'
services:
  kafka:
    image: eventuateio/eventuate-kafka:0.15.0.BUILD-SNAPSHOT
    hostname: kafka
    networks:
      - coderedemption
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
      KAFKA_HEAP_OPTS: -Xmx192m
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.apache.kafka=ERROR,kafka=ERROR,kafka.cluster=ERROR,kafka.controller=ERROR,kafka.coordinator=ERROR,kafka.log=ERROR,kafka.server=ERROR,kafka.zookeeper=ERROR,state.change.logger=ERROR
    volumes:
      - /opt/coderedemption/zookeeper:/var/lib/zookeeper/data
  zookeeper:
    image: eventuateio/eventuate-zookeeper:0.15.0.BUILD-SNAPSHOT
    hostname: zookeeper
    networks:
      - coderedemption
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - /opt/coderedemption/kafka:/var/lib/kafka/data

networks:
  coderedemption:
    external: true