version: '3.8'
services:
  order-service:
    image: docker.io/makalaoscar/oscar-docker:cr-order-service
    hostname: order-service
    networks:
      - coderedemption
    ports:
      - "9876:9876"
    depends_on:
      - mysql
      - kafka
      - cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb/cr_order_service
      SPRING_DATASOURCE_USERNAME: cr_order_service_user
      SPRING_DATASOURCE_PASSWORD: cr_order_service_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_DATABASE_SCHEMA: cr_order_service
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.JWK-SET-URI: http://keycloak:8080/auth/realms/azamCodeRedemption/protocol/openid-connect/certs

  user-service:
    image: docker.io/makalaoscar/oscar-docker:cr-user-service
    hostname: user-service
    depends_on:
      - keycloak
    networks:
      - coderedemption
    ports:
      - "2678:2678"
    environment:
      SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.JWK-SET-URI: http://keycloak:8080/auth/realms/azamCodeRedemption/protocol/openid-connect/certs
  voucher-history-service:
    image: docker.io/makalaoscar/oscar-docker:cr-voucher-history-service
    hostname: voucher-history-service
    networks:
      - coderedemption
    ports:
      - "3333:3333"
    depends_on:
      - mongo
      - kafka
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.JWK-SET-URI: http://keycloak:8080/auth/realms/azamCodeRedemption/protocol/openid-connect/certs
      SPRING.DATA.MONGODB.URI: mongodb://mongo:27017/VoucherHistoryDb

  notification-service:
    image: makalaoscar/oscar-docker:cr-notification-service
    hostname: notification-service
    networks:
      - coderedemption
    expose:
      - "9875"
    depends_on:
      - mariadb
      - kafka
      - cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb/cr_notification_service
      SPRING_DATASOURCE_USERNAME: cr_notification_service_user
      SPRING_DATASOURCE_PASSWORD: cr_notification_service_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_DATABASE_SCHEMA: cr_notification_service
      VENDORS_DISBURSEMENT_ENDPOINT: https://g8x2j.api.infobip.com/sms/2/text/advanced
      HEADERS_AUTHORIZATION: App f55987828ca82b8559f2a9f7291d0c49-d6d973b0-105b-424c-9372-4103386f0de5
      SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.JWK-SET-URI: http://keycloak:8080/auth/realms/azamCodeRedemption/protocol/openid-connect/certs

  account-service:
    image: makalaoscar/oscar-docker:cr-account-service
    hostname: account-service
    networks:
      - coderedemption
    expose:
      - "9878"
    depends_on:
      - mariadb
      - kafka
      - cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb/cr_account_service
      SPRING_DATASOURCE_USERNAME: cr_account_service_user
      SPRING_DATASOURCE_PASSWORD: cr_account_service_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_DATABASE_SCHEMA: cr_account_service
      SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.JWK-SET-URI: http://keycloak:8080/auth/realms/azamCodeRedemption/protocol/openid-connect/certs
      VENDORS_DISBURSEMENT_ENDPOINT: https://172.16.1.6:8243/codedisburse/1.0.0
      VENDORS_DISBURSEMENT_HEADERS_Authorization: Bearer 0878044f-a543-3760-8b7e-b48213052ac5
      VENDORS_DISBURSEMENT_TEMPLATE: |
        {"serviceCode":"CODEDISB","bearerCode":"USSD","transactionAmount":"#{amount}","currency":"101","externalReferenceId":"#{transactionId}","source":"CODE_REDEMPTION","remarks":"Codedisburse","transactionMode":"Codedisburse","initiator":"transactor","language":"sw","transactor":{"idType":"mobileNumber","idValue":"780100100","productId":"12","mpin":"1357","tpin":"1357"},"receiver":{"idType":"mobileNumber","idValue":"#{mobile}","productId":"12"}}
  voucher-service:
    image: docker.io/makalaoscar/oscar-docker:cr-voucher-service
    hostname: voucher-service
    networks:
      - coderedemption
    ports:
      - "9877:9877"
    depends_on:
      - mariadb
      - kafka
      - cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb/cr_voucher_service
      SPRING_DATASOURCE_USERNAME: cr_voucher_service_user
      SPRING_DATASOURCE_PASSWORD: cr_voucher_service_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_DATABASE_SCHEMA: cr_voucher_service
      SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.JWK-SET-URI: http://keycloak:8080/auth/realms/azamCodeRedemption/protocol/openid-connect/certs

networks:
  coderedemption:
    external: true