apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service
  namespace: code-redemption
  labels:
    app: notification-service
data:
  application.yaml: |-
    spring:
      application:
        name: cr-notification-service
      datasource:
        url: jdbc:mysql://172.16.115.6:3306/cr_notification_service
        username: cr_notification_service_user
        password: cr_notification_service_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          max-lifetime: 10
      jpa:
        generate-ddl: true
    eventuatelocal:
      kafka:
        bootstrap:
          servers: kafka:29092
      zookeeper:
        connection:
          string: kafka-zk:2181
    eventuate:
      database:
        schema: cr_notification_service
    logging:
      level:
        org.springframework.orm.jpa: INFO
        org.hibernate.SQL: DEBUG
        io.eventuate: DEBUG
        io.eventuate.tram: DEBUG
        com.divforce.cr: DEBUG
    server:
      port: 9875


    notification:
      endpoint: https://g8x2j.api.infobip.com/sms/2/text/advanced
      headers:
        Authorization: App f55987828ca82b8559f2a9f7291d0c49-d6d973b0-105b-424c-9372-4103386f0de5
      template: |
        {
            "messages": [
                {
                    "from": "AzamPesa",
                    "destinations": [
                        {
                            "to": "#{msisdn}"
                        }
                    ],
                    "text": "#{text}"
                }
            ]
        }
      messages:
        voucher_already_used:
          en: Dear customer your lucky number has been used. Keep buying azam drinks so you can get a refund on your Azampesa account and enjoy our services.
          sw: Ndugu mteja namba yako ya bahati imetumika. Endelea kununua vinywaji vya azam uweze kupata rejesho kwenye akaunti yako ya Azampesa na ufuruhie huduma zetu.
        campaign_not_active:
          en: Dear customer your lucky number has not been successful. Keep buying azam drinks so you can get a refund on your Azampesa account and enjoy our services.
          sw: Ndugu mteja namba yako ya bahati haijafanikiwa. Endelea kununua vinywaji vya azam uweze kupata rejesho kwenye akaunti yako ya Azampesa na ufuruhie huduma zetu.
        no_such_voucher:
          en: Dear customer your lucky number has not been successful. Keep buying azam drinks so you can get a refund on your Azampesa account and enjoy our services.
          sw: Ndugu mteja namba yako ya bahati haijafanikiwa. Endelea kununua vinywaji vya azam uweze kupata rejesho kwenye akaunti yako ya Azampesa na ufuruhie huduma zetu.
        voucher_expired:
          en: Dear customer your lucky number has not been successful. Keep buying azam drinks so you can get a refund on your Azampesa account and enjoy our services.
          sw: Ndugu mteja namba yako ya bahati haijafanikiwa. Endelea kununua vinywaji vya azam uweze kupata rejesho kwenye akaunti yako ya Azampesa na ufuruhie huduma zetu.
        voucher_redeemed:
          en: Congratulations! You have been refunded Tsh 500 to your Azampesa account. Your balance is 500.00. Dial *150*08# to use Azampesa and enjoy our services
          sw: Hongera! umerudishiwa Tsh 500 kwenye akaunti yako ya azampesa. Salio lako ni 500.00.Bonyeza *150*08# kutumia Azampesa na ufurahie huduma zetu.
        system_failure:
          en: Dear Customer please try again later , service is currently  not avaibale
          sw: Ndugu Mteja jaribu tena baadae, huduma haipatikani kwa sasa